In [1]:
import os
import numpy as np
from tqdm import tqdm

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
dists_fn = './output_data/dist.csv'
import pandas as pd
df = pd.read_csv(dists_fn)

In [3]:
len(df.graph.unique())

4032

In [4]:
df.loc[(df.graph=='GD95_a') & (df.s == 29)]

,graph,algo,seed,s,t,dist,time_dist,search_space
657019,GD95_a,bfs,3404785993,29,28,2,0.000300,9
657052,GD95_a,bfs,3404785993,29,27,1,0.000321,3
657063,GD95_a,bfs,3404785993,29,24,3,0.000621,40
657096,GD95_a,bfs,3404785993,29,17,5,0.000962,95
657119,GD95_a,bfs_bi_balanced,3404785993,29,28,2,0.000712,5
657152,GD95_a,bfs_bi_balanced,3404785993,29,27,1,0.000601,2
657163,GD95_a,bfs_bi_balanced,3404785993,29,24,3,0.004759,13
657196,GD95_a,bfs_bi_balanced,3404785993,29,17,5,0.001122,17
657219,GD95_a,bfs_bi_always_swap,3404785993,29,28,2,0.000701,6
657252,GD95_a,bfs_bi_always_swap,3404785993,29,27,1,0.000611,3
657263,GD95_a,bfs_bi_always_swap,3404785993,29,24,3,0.004689,13
657296,GD95_a,bfs_bi_always_swap,3404785993,29,17,5,0.000872,23
657319,GD95_a,bfs_bi_node,3404785993,29,28,2,0.000701,5
657352,GD95_a,bfs_bi_node,3404785993,29,27,1,0.000741,2
657363,GD95_a,bfs_bi_node,3404785993,29,24,4,0.005320,13
657396,GD95_a,bfs_bi_node,3404785993,29,17,5,0.000841,14
657419,GD95_a,bfs_bi_node_exact,3404785993,29,28,2,0.000822,8
657452,GD95_a,bfs_bi_node_exact,3404785993,29,27,1,0.000692,3
657463,GD95_a,bfs_bi_node_exact,3404785993,29,24,3,0.001012,28
657496,GD95_a,bfs_bi_node_exact,3404785993,29,17,5,0.000972,20

In [5]:
2016000/4032

500.0

In [6]:
df.columns

Index(['graph', 'algo', 'seed', 's', 't', 'dist', 'time_dist', 'search_space'], dtype='object')

In [7]:
df.algo.unique()

array(['bfs', 'bfs_bi_balanced', 'bfs_bi_always_swap', 'bfs_bi_node',
       'bfs_bi_node_exact'], dtype=object)

In [8]:
temp = lambda algo: df.loc[(df.algo == algo) & (df.graph.isin(['08blocks', '1138_bus', '130bit', '145bit', '162bit', '176bit',
       '192bit', '208bit', '2D_27628_bjtcai', '2D_54019_highK']))]\
    .groupby(['graph', 's', 't']).dist.unique().apply(lambda x: x[0])

foo = temp('bfs_bi_balanced')
bar = temp('bfs_bi_node_exact')
baz = temp('bfs_bi_node')

In [15]:
graphs_small_first = sizes.sort_values('n').graph
graphs_small_first

1363                      Letter-med
38                          COIL-RAG
1362                     Letter-high
1265                     Fingerprint
5177    reptilia-tortoise-network-pv
                    ...
5077                          pds-80
1945                         dbpedia
5310         soc-twitter-follows-mun
4943           munmun_twitter_social
1485       aff-dbpedia-users2country
Name: graph, Length: 5487, dtype: object

In [16]:
bad_graphs = []

for graph in tqdm(graphs_small_first):
    a = df.loc[(df.algo == 'bfs_bi_balanced') & (df.graph==graph)]\
    .groupby(['graph', 's', 't']).dist.unique().apply(lambda x: x[0])
    b = df.loc[(df.algo == 'bfs_bi_node_exact') & (df.graph==graph)]\
    .groupby(['graph', 's', 't']).dist.unique().apply(lambda x: x[0])
    if not np.all(a == b):
        bad_graphs.append(graph)
        print(graph)

    if len(bad_graphs) > 4:
        break

  1%|▌                                                                                | 39/5487 [00:08<19:26,  4.67it/s]

KeyboardInterrupt:

In [33]:
bad_graphs

['Letter-med',
 'COIL-RAG',
 'Letter-high',
 'Fingerprint',
 'reptilia-tortoise-network-pv']

In [34]:
temp = lambda algo: df.loc[(df.algo == algo) & (df.graph.isin(bad_graphs))]\
    .groupby(['graph', 's', 't']).dist.unique().apply(lambda x: x[0])

foo = temp('bfs_bi_balanced')
bar = temp('bfs_bi_node_exact')
baz = temp('bfs_bi_node')

In [35]:
foo[foo != bar]

graph                         s   t
COIL-RAG                      0   3     2
                              3   4     1
                              5   6     1
                              6   5     1
Fingerprint                   0   5     5
                                       ..
reptilia-tortoise-network-pv  17  14    3
                                  16    3
                              18  10    3
                              19  13    5
                              20  19    2
Name: dist, Length: 131, dtype: int64

In [36]:
bar[foo!= bar]

graph                         s   t
COIL-RAG                      0   3     4294967295
                              3   4              2
                              5   6              3
                              6   5              3
Fingerprint                   0   5     4294967295
                                           ...
reptilia-tortoise-network-pv  17  14             5
                                  16             5
                              18  10    4294967295
                              19  13    4294967295
                              20  19             3
Name: dist, Length: 131, dtype: int64

In [19]:
baz[foo != bar][:10]

graph    s   t
DD_g789  29  27    6
GD01_c   14  32    5
GD95_a   29  24    4
GD98_a   14  31    6
         20  13    4
         25  20    4
         26  31    6
         31  26    6
             27    6
Hamrle1  3   23    4
Name: dist, dtype: int64

In [37]:
sizes[sizes.graph.isin(bad_graphs)]

                             graph   n   m
38                        COIL-RAG   8  12
1265                   Fingerprint  18  17
1362                   Letter-high   9   9
1363                    Letter-med   8   7
5177  reptilia-tortoise-network-pv  22  49

## Can we find a small graph?

In [12]:
sizes = pd.read_csv('./output_data/size.csv')

In [13]:
df = pd.merge(df, sizes, on='graph')

In [14]:
df

,graph,algo,seed,s,t,dist,time_dist,search_space,n,m
0,08blocks,bfs,3404785993,4,23,2,0.001623,40,38,73
1,08blocks,bfs,3404785993,9,32,2,0.000802,40,38,73
2,08blocks,bfs,3404785993,17,24,2,0.000701,40,38,73
3,08blocks,bfs,3404785993,12,5,2,0.000672,40,38,73
4,08blocks,bfs,3404785993,26,32,2,0.000572,40,38,73
...,...,...,...,...,...,...,...,...,...,...
2015995,wing_nodal,bfs_bi_node_exact,3404785993,2870,8809,12,0.125438,21765,10937,75488
2015996,wing_nodal,bfs_bi_node_exact,3404785993,9061,5268,13,0.122813,24879,10937,75488
2015997,wing_nodal,bfs_bi_node_exact,3404785993,2090,10140,13,0.095511,17910,10937,75488
2015998,wing_nodal,bfs_bi_node_exact,3404785993,3095,9533,10,0.061306,11509,10937,75488
2015999,wing_nodal,bfs_bi_node_exact,3404785993,7537,2580,13,0.128324,23783,10937,75488

## What is going on with DD_g714?

In [77]:
!pip install networkit

Collecting networkit
  Downloading networkit-10.1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 9.4 MB/s eta 0:00:0000:0100:01m
Requirement already satisfied: numpy in /home/benji/benjienv/lib/python3.10/site-packages (from networkit) (1.26.1)
Collecting scipy
  Downloading scipy-1.11.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.4/36.4 MB 56.3 MB/s eta 0:00:0000:0100:01
Installing collected packages: scipy, networkit
Successfully installed networkit-10.1 scipy-1.11.3

In [78]:
import networkit as nk

In [98]:
g_fn = 'input_data/DD_g714'
with open(g_fn) as file:
    lines = list(map(lambda x: x[:-1].split(' '), file.readlines()))
    lines = [list(map(int, y)) for y in lines]

n, m = lines[0]
g = nk.Graph(n)
for _, u, v in lines[1:]:
    _ = g.addEdge(u, v)

def nhbs(u):
    return set(g.iterNeighbors(u))

In [104]:
nhbs(5)

{2, 23, 24, 26, 27}

In [105]:
nhbs(24)

{5, 20, 23, 25, 26, 27}

In [106]:
nhbs(17)

{10, 13, 16, 18, 19, 20}

In [107]:
nhbs(18)

{13, 16, 17, 19}

In [128]:
nhbs(13)

{9, 10, 12, 16, 17, 18}

In [129]:
nhbs(20)

{17, 19, 23, 24, 25}

In [21]:
import networkit as nk

g_fn = 'input_data/DD_g789'
with open(g_fn) as file:
    lines = list(map(lambda x: x[:-1].split(' '), file.readlines()))
    lines = [list(map(int, y)) for y in lines]

n, m = lines[0]
g = nk.Graph(n)
for _, u, v in lines[1:]:
    _ = g.addEdge(u, v)

def nhbs(u):
    return set(g.iterNeighbors(u))

In [22]:
nhbs(22)

{6, 20, 30}

In [23]:
nhbs(30)

{20, 22, 23, 28}

In [44]:
import networkit as nk

g_fn = 'input_data/GD95_a'
with open(g_fn) as file:
    lines = list(map(lambda x: x[:-1].split(' '), file.readlines()))
    lines = [list(map(int, y)) for y in lines]

n, m = lines[0]
g = nk.Graph(n)
for _, u, v in lines[1:]:
    _ = g.addEdge(u, v)

def nhbs(u):
    return set(g.iterNeighbors(u))

In [46]:
nhbs(12)

{10, 18, 26, 27, 28, 29}

In [47]:
nhbs(27)

{11, 12, 29, 32}

## Ok let's look again at dists